apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: todoapp-claim
spec:
  storageClassName: todoapp-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
